In [698]:
import pandas as pd
films = pd.read_csv('movies_clean.csv')

##Dropping columns

In [726]:
films

,genres,id,original_language,original_title,overview,popularity,production_companies,production_countries,runtime,spoken_languages,title,vote_average,vote_count,cast,crew,year,director,director_gender,prod_countries
0,"Comedy, Romance",11860,English,Sabrina,An ugly duckling having undergone a remarkable...,6.677277,"[{'name': 'Paramount Pictures', 'id': 4}, {'na...","Germany, United States of America",127.0,2,Sabrina,6.2,141.0,"[{'cast_id': 1, 'character': 'Linus Larrabee',...","[{'credit_id': '52fe44959251416c75039da9', 'de...",1995,Sydney Pollack,male,Germany
1,"Comedy, Horror",12110,English,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.430331,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","France, United States of America",88.0,2,Dracula: Dead and Loving It,5.7,210.0,"[{'cast_id': 9, 'character': 'Count Dracula', ...","[{'credit_id': '52fe44b79251416c7503e7fb', 'de...",1995,Mel Brooks,male,France
2,"Action, Adventure",1408,English,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.284477,"[{'name': 'Le Studio Canal+', 'id': 183}, {'na...","Germany, France, Italy, United States of America",119.0,2,Cutthroat Island,5.7,137.0,"[{'cast_id': 1, 'character': 'Morgan Adams', '...","[{'credit_id': '52fe42f4c3a36847f802f69f', 'de...",1995,Renny Harlin,male,France
3,"Drama, Crime",524,English,Casino,The life of the gambling paradise – Las Vegas ...,10.137389,"[{'name': 'Universal Pictures', 'id': 33}, {'n...","France, United States of America",178.0,1,Casino,7.8,1343.0,"[{'cast_id': 4, 'character': ""Sam 'Ace' Rothst...","[{'credit_id': '52fe424dc3a36847f80139cd', 'de...",1995,Martin Scorsese,male,France
4,"Drama, Romance",4584,English,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.673167,"[{'name': 'Columbia Pictures Corporation', 'id...","United Kingdom, United States of America",136.0,1,Sense and Sensibility,7.2,364.0,"[{'cast_id': 6, 'character': 'Marianne Dashwoo...","[{'credit_id': '52fe43cec3a36847f807101f', 'de...",1995,Ang Lee,male,United Kingdom
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9773,"Drama, Thriller, Mystery, Horror",365432,English,The Sublet,The Sublet is a suspense driven psychological ...,1.339355,"[{'name': 'Black Fawn Films', 'id': 9315}, {'n...",Canada,82.0,2,The Sublet,6.5,4.0,"[{'cast_id': 1, 'character': 'Joanna', 'credit...","[{'credit_id': '562e344bc3a3681b5c00ab29', 'de...",2015,John Ainslie,male,Canada
9774,"Action, Thriller, Mystery, Horror",45527,English,The Final Storm,A stranger named Silas flees from a devastatin...,1.270832,[{'name': 'Boll Kino Beteiligungs GmbH & Co. K...,"Germany, Canada",92.0,1,The Final Storm,3.7,11.0,"[{'cast_id': 1, 'character': 'Gillian Grady', ...","[{'credit_id': '52fe46c7c3a36847f81119a1', 'de...",2010,Uwe Boll,male,Canada
9775,"Drama, Family, TV Movie",39562,English,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",0.767762,[],Canada,89.0,1,To Be Fat Like Me,5.0,12.0,"[{'cast_id': 1, 'character': 'Alyson', 'credit...","[{'credit_id': '562ec44ec3a3681b5900bac2', 'de...",2007,Douglas Barr,male,Canada
9776,Comedy,14008,English,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,4.392389,"[{'name': 'Walt Disney Television', 'id': 670}...","United States of America, Canada",101.0,1,Cadet Kelly,5.2,145.0,"[{'cast_id': 1, 'character': 'Kelly Collins', ...","[{'credit_id': '52fe45c29251416c75061803', 'de...",2002,Larry Shaw,male,Canada
9777,"Action, Drama, Romance",30840,English,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,"[{'name': 'Westdeutscher Rundfunk (WDR)', 'id'...","Germany, United Kingdom, United States of Amer...",104.0,1,Robin Hood,5.7,26.0,"[{'cast_id': 1, 'character': 'Sir Robert Hode'...","[{'credit_id': '52fe44439251416c9100a899', 'de...",1991,John Irvin,male,Canada

In [699]:
films.drop(columns=[ 'release_date', 'poster_path'], inplace=True)

In [723]:
films.isnull().sum()

genres                  0
id                      0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
runtime                 0
spoken_languages        0
title                   0
vote_average            0
vote_count              0
cast                    0
crew                    0
year                    0
director                0
director_gender         0
prod_countries          0
dtype: int64

In [700]:
films[films['director_gender']== 'female']

,genres,id,original_language,original_title,overview,popularity,production_companies,production_countries,runtime,spoken_languages,title,vote_average,vote_count,cast,crew,year,director,director_gender
13,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",8391,English,When Night Is Falling,"A prudish woman, working on tenure as a litera...",3.302524,[{'name': 'Alliance Communications Corporation...,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",96.0,1,When Night Is Falling,5.9,10.0,"[{'cast_id': 1, 'character': 'Camille Baker', ...","[{'credit_id': '52fe44a4c3a36847f80a1e53', 'de...",1995,Patricia Rozema,female
18,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",4482,French,Gazon maudit,"After learning of her husband's infidelities, ...",2.518051,"[{'name': 'Renn Productions', 'id': 82}, {'nam...","[{'iso_3166_1': 'FR', 'name': 'France'}]",95.0,2,French Twist,6.0,43.0,"[{'cast_id': 4, 'character': 'Loli', 'credit_i...","[{'credit_id': '52fe43c5c3a36847f806e5f3', 'de...",1995,Josiane Balasko,female
25,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",11907,German,Keiner liebt mich,No overview found.,1.015068,[],"[{'iso_3166_1': 'DE', 'name': 'Germany'}]",104.0,1,Nobody Loves Me,5.1,5.0,"[{'cast_id': 1, 'character': 'Fanny Fink', 'cr...","[{'credit_id': '52fe449f9251416c7503b371', 'de...",1994,Doris Dörrie,female
44,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",36834,English,Total Eclipse,"Young, wild poet Arthur Rimbaud and his mentor...",4.546552,[{'name': 'Société Française de Production (SF...,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",111.0,1,Total Eclipse,6.5,112.0,"[{'cast_id': 1, 'character': 'Arthur Rimbaud',...","[{'credit_id': '52fe460f9251416c91047b0f', 'de...",1995,Agnieszka Holland,female
62,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",40156,English,Priest,Father Greg Pilkington (Linus Roache) is torn ...,1.881932,"[{'name': 'BBC Films', 'id': 288}, {'name': 'P...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",98.0,1,Priest,6.4,32.0,"[{'cast_id': 2, 'character': 'Father Greg Pilk...","[{'credit_id': '52fe4583c3a36847f80cb96b', 'de...",1994,Antonia Bird,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9747,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",182981,Dutch,Nude Area,"Naomi, a fifteen year-old Dutch girl from Sout...",0.420688,"[{'name': 'Canal+', 'id': 5358}, {'name': 'App...","[{'iso_3166_1': 'NL', 'name': 'Netherlands'}, ...",73.0,1,Nude Area,5.0,2.0,"[{'cast_id': 2, 'character': 'Naomi', 'credit_...","[{'credit_id': '52fe4c929251416c7511ea9d', 'de...",2014,Urszula Antoniak,female
9751,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",30019,Norwegian,Upperdog,"As young children, half-siblings Axel and Yann...",1.056898,"[{'name': 'Riva Filmproduktion', 'id': 2677}, ...","[{'iso_3166_1': 'NO', 'name': 'Norway'}]",95.0,1,Upperdog,6.9,5.0,"[{'cast_id': 3, 'character': 'Axel', 'credit_i...","[{'credit_id': '571e27699251411ca700149b', 'de...",2009,Sara Johnsen,female
9755,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",366505,Spanish,El olivo,Alma’s family has been producing quality olive...,2.541633,"[{'name': 'Eurimages', 'id': 850}, {'name': 'F...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",96.0,1,The Olive Tree,6.5,38.0,"[{'cast_id': 2, 'character': 'Alcachofas', 'cr...","[{'credit_id': '572af90ec3a3685429000988', 'de...",2016,Icíar Bollaín,female
9763,[],408624,English,A Death in the Gunj,A sensitive university student unraveling whil...,0.516993,"[{'name': 'Studioz IDrream', 'id': 85800}, {'n...","[{'iso_3166_1': 'IN', 'name': 'India'}]",110.0,2,A Death in the Gunj,7.0,5.0,"[{'cast_id': 1, 'character': 'Shyamlal Chatter...","[{'credit_id': '58877d529251415ff70053e7', 'de...",2016,Konkona Sen Sharma,female
9771,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",63281,English,Про любоff,"У девушки Даши, приехавшей с подругой «покорят...",0.121844,"[{'name': 'Profit', 'id': 21163}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",107.0,1,Pro Lyuboff,4.0,3.0,"[{'cast_id': 1001, 'character': 'Vlad', 'credi...","[{'credit_id': '52fe46a3c3a368484e09b9fd', 'de...",2010,Olga Subbotina,female

In [701]:
#No null values 
films.isna().sum()

genres                  0
id                      0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
runtime                 0
spoken_languages        0
title                   0
vote_average            0
vote_count              0
cast                    0
crew                    0
year                    0
director                0
director_gender         0
dtype: int64

In [702]:
films[films['director_gender']== 'female']

,genres,id,original_language,original_title,overview,popularity,production_companies,production_countries,runtime,spoken_languages,title,vote_average,vote_count,cast,crew,year,director,director_gender
13,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",8391,English,When Night Is Falling,"A prudish woman, working on tenure as a litera...",3.302524,[{'name': 'Alliance Communications Corporation...,"[{'iso_3166_1': 'CA', 'name': 'Canada'}]",96.0,1,When Night Is Falling,5.9,10.0,"[{'cast_id': 1, 'character': 'Camille Baker', ...","[{'credit_id': '52fe44a4c3a36847f80a1e53', 'de...",1995,Patricia Rozema,female
18,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",4482,French,Gazon maudit,"After learning of her husband's infidelities, ...",2.518051,"[{'name': 'Renn Productions', 'id': 82}, {'nam...","[{'iso_3166_1': 'FR', 'name': 'France'}]",95.0,2,French Twist,6.0,43.0,"[{'cast_id': 4, 'character': 'Loli', 'credit_i...","[{'credit_id': '52fe43c5c3a36847f806e5f3', 'de...",1995,Josiane Balasko,female
25,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",11907,German,Keiner liebt mich,No overview found.,1.015068,[],"[{'iso_3166_1': 'DE', 'name': 'Germany'}]",104.0,1,Nobody Loves Me,5.1,5.0,"[{'cast_id': 1, 'character': 'Fanny Fink', 'cr...","[{'credit_id': '52fe449f9251416c7503b371', 'de...",1994,Doris Dörrie,female
44,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",36834,English,Total Eclipse,"Young, wild poet Arthur Rimbaud and his mentor...",4.546552,[{'name': 'Société Française de Production (SF...,"[{'iso_3166_1': 'FR', 'name': 'France'}, {'iso...",111.0,1,Total Eclipse,6.5,112.0,"[{'cast_id': 1, 'character': 'Arthur Rimbaud',...","[{'credit_id': '52fe460f9251416c91047b0f', 'de...",1995,Agnieszka Holland,female
62,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",40156,English,Priest,Father Greg Pilkington (Linus Roache) is torn ...,1.881932,"[{'name': 'BBC Films', 'id': 288}, {'name': 'P...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",98.0,1,Priest,6.4,32.0,"[{'cast_id': 2, 'character': 'Father Greg Pilk...","[{'credit_id': '52fe4583c3a36847f80cb96b', 'de...",1994,Antonia Bird,female
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9747,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",182981,Dutch,Nude Area,"Naomi, a fifteen year-old Dutch girl from Sout...",0.420688,"[{'name': 'Canal+', 'id': 5358}, {'name': 'App...","[{'iso_3166_1': 'NL', 'name': 'Netherlands'}, ...",73.0,1,Nude Area,5.0,2.0,"[{'cast_id': 2, 'character': 'Naomi', 'credit_...","[{'credit_id': '52fe4c929251416c7511ea9d', 'de...",2014,Urszula Antoniak,female
9751,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",30019,Norwegian,Upperdog,"As young children, half-siblings Axel and Yann...",1.056898,"[{'name': 'Riva Filmproduktion', 'id': 2677}, ...","[{'iso_3166_1': 'NO', 'name': 'Norway'}]",95.0,1,Upperdog,6.9,5.0,"[{'cast_id': 3, 'character': 'Axel', 'credit_i...","[{'credit_id': '571e27699251411ca700149b', 'de...",2009,Sara Johnsen,female
9755,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",366505,Spanish,El olivo,Alma’s family has been producing quality olive...,2.541633,"[{'name': 'Eurimages', 'id': 850}, {'name': 'F...","[{'iso_3166_1': 'DE', 'name': 'Germany'}, {'is...",96.0,1,The Olive Tree,6.5,38.0,"[{'cast_id': 2, 'character': 'Alcachofas', 'cr...","[{'credit_id': '572af90ec3a3685429000988', 'de...",2016,Icíar Bollaín,female
9763,[],408624,English,A Death in the Gunj,A sensitive university student unraveling whil...,0.516993,"[{'name': 'Studioz IDrream', 'id': 85800}, {'n...","[{'iso_3166_1': 'IN', 'name': 'India'}]",110.0,2,A Death in the Gunj,7.0,5.0,"[{'cast_id': 1, 'character': 'Shyamlal Chatter...","[{'credit_id': '58877d529251415ff70053e7', 'de...",2016,Konkona Sen Sharma,female
9771,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",63281,English,Про любоff,"У девушки Даши, приехавшей с подругой «покорят...",0.121844,"[{'name': 'Profit', 'id': 21163}]","[{'iso_3166_1': 'RU', 'name': 'Russia'}]",107.0,1,Pro Lyuboff,4.0,3.0,"[{'cast_id': 1001, 'character': 'Vlad', 'credi...","[{'credit_id': '52fe46a3c3a368484e09b9fd', 'de...",2010,Olga Subbotina,female

In [703]:
films.drop_duplicates(subset='id', inplace=True)
films['id'].value_counts()

11860     1
167956    1
68744     1
44023     1
84508     1
         ..
43389     1
14298     1
9381      1
16182     1
30840     1
Name: id, Length: 9769, dtype: int64

In [704]:
films['vote_average'].sort_values()

6057     0.0
3785     0.0
8053     0.0
9301     0.0
3081     0.0
        ...
8434    10.0
5357    10.0
4987    10.0
3960    10.0
7827    10.0
Name: vote_average, Length: 9769, dtype: float64

In [705]:
# I decided to drop this column, as well as "vote_count" because I saw that "Call Me by Your Name", a very popular film, had a vote average 0. I will keep the column "popularity" which is more reliable, with a value of 4.300874.
films[films['vote_average'] == 0.0]
#male.drop(columns=['vote_average','vote_count'], inplace=True)

,genres,id,original_language,original_title,overview,popularity,production_companies,production_countries,runtime,spoken_languages,title,vote_average,vote_count,cast,crew,year,director,director_gender
3081,"[{'id': 18, 'name': 'Drama'}, {'id': 10770, 'n...",111744,English,Joe and Max,True story of boxers Joe Louis and Max Schmeli...,1.669115,[],"[{'iso_3166_1': 'US', 'name': 'United States o...",109.0,3,Joe and Max,0.0,1.0,"[{'cast_id': 1001, 'character': 'Joe Louis', '...","[{'credit_id': '593caed79251410587015f8b', 'de...",2002,Steve James,male
3785,"[{'id': 35, 'name': 'Comedy'}]",252407,English,Ich und Er,A man's enthusiastic penis starts talking to h...,0.645652,"[{'name': 'Neue Constantin Film', 'id': 13096}]","[{'iso_3166_1': 'DE', 'name': 'Germany'}]",93.0,0,Me and Him,0.0,1.0,"[{'cast_id': 1, 'character': 'Bert Uttanzi', '...","[{'credit_id': '5892039a9251412dc8008a19', 'de...",1988,Doris Dörrie,female
4322,"[{'id': 18, 'name': 'Drama'}, {'id': 14, 'name...",63702,French,Liliom,Two women love the same man in a world of few ...,0.157182,"[{'name': 'Les Productions Fox Europa', 'id': ...","[{'iso_3166_1': 'FR', 'name': 'France'}]",118.0,1,Liliom,0.0,2.0,"[{'cast_id': 4, 'character': 'Liliom Zadowski'...","[{'credit_id': '52fe46b7c3a368484e09ffc1', 'de...",1934,Fritz Lang,male
6057,"[{'id': 18, 'name': 'Drama'}]",56178,French,Prix de beauté,"Lucienne, typist and gorgeous bathing beauty, ...",0.444066,[],"[{'iso_3166_1': 'FR', 'name': 'France'}]",93.0,1,Beauty Prize,0.0,1.0,"[{'cast_id': 1001, 'character': 'Lucienne', 'c...","[{'credit_id': '52fe48f3c3a36847f8181d0b', 'de...",1930,Augusto Genina,male
6405,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",66963,French,Lucrèce Borgia,French silent film pioneer Abel Gance directs ...,0.142167,[],"[{'iso_3166_1': 'FR', 'name': 'France'}]",93.0,1,Lucrezia Borgia,0.0,2.0,"[{'cast_id': 2, 'character': 'Lucrezia Borgia'...","[{'credit_id': '52fe4752c3a368484e0c089b', 'de...",1935,Abel Gance,male
6772,"[{'id': 12, 'name': 'Adventure'}]",95029,English,The Hellfire Club,Years after fleeing his ancestral home with hi...,0.177689,"[{'name': 'New World Productions', 'id': 45641}]","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'}]",90.0,1,The Hellfire Club,0.0,1.0,"[{'cast_id': 4, 'character': 'Jason', 'credit_...","[{'credit_id': '54cf9dbc9251415cb8007196', 'de...",1961,Robert S. Baker,male
7141,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",212934,English,Behind the Camera: The Unauthorized Story of '...,An inside look at the ABC sitcom which turned ...,0.088172,"[{'name': 'NBC Studios', 'id': 7928}, {'name':...","[{'iso_3166_1': 'CA', 'name': 'Canada'}]",120.0,1,Behind the Camera: The Unauthorized Story of '...,0.0,1.0,"[{'cast_id': 2, 'character': 'Robin Williams',...","[{'credit_id': '52fe4dbac3a368484e1f9ab9', 'de...",2005,Neill Fearnley,male
7426,"[{'id': 10770, 'name': 'TV Movie'}, {'id': 37,...",86543,English,Rose Hill,Four orphan boys running from the law in New Y...,0.625766,"[{'name': 'Hallmark Hall of Fame Productions',...","[{'iso_3166_1': 'US', 'name': 'United States o...",90.0,1,Rose Hill,0.0,1.0,"[{'cast_id': 2, 'character': 'Mary Rose Claybo...","[{'credit_id': '56d071a6c3a3681e44007122', 'de...",1997,Christopher Cain,male
8053,"[{'id': 18, 'name': 'Drama'}]",299143,Italian,La porta del cielo,Episodic film about the lives of a few people ...,0.040130,"[{'name': 'Orbis Film', 'id': 36389}, {'name':...","[{'iso_3166_1': 'IT', 'name': 'Italy'}]",88.0,1,The Gate of Heaven,0.0,1.0,"[{'cast_id': 0, 'character': 'The nurse', 'cre...","[{'credit_id': '5812de86c3a3687aa0020f68', 'de...",1945,Vittorio De Sica,male
9253,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",398818,English,Call Me by Your Name,Elio Perlman is spending the summer with his f...,4.300874,"[{'name': 'Sony Pictures Classics', 'id': 58},...","[{'iso_3166_1': 'BR', 'name': 'Brazil'}, {'iso...",130.0,3,Call Me by Your Name,0.0,18.0,"[{'cast_id': 4, 'character': 'Elio Perlman', '...","[{'credit_id': '5742ea0ec3a3686c8c001a6e', 'de...",2017,Luca Guadagnino,male
9301,"[{'id': 18, 'name': 'Drama'}]",429732,French,"Ana, mon amour",Toma and Ana meet as students in the literatur...,2.160256,"[{'name': 'Sophie Dulac Productions', 'id': 18...","[{'iso_3166_1': 'RO', 'name': 'Romania'}, {'is...",127.0,2,"Ana, My Love",0.0,3.0,"[{'cast_id': 5, 'character': 'Toma', 'credit_i...","[{'credit_id': '589fd3dfc3a3684e7b000278', 'de...",2017,Călin Peter Netzer,male

In [706]:
#I checked the relevance of "popularity" column by checking the movies with lowest and highest rates.
films['popularity'].sort_values()
films['popularity'].sort_values(ascending=False)
films.loc[9462]

genres                  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...
id                                                                 339403
original_language                                                 English
original_title                                                Baby Driver
overview                After being coerced into working for a crime b...
popularity                                                     228.032744
production_companies    [{'name': 'Big Talk Productions', 'id': 443}, ...
production_countries    [{'iso_3166_1': 'GB', 'name': 'United Kingdom'...
runtime                                                             113.0
spoken_languages                                                        1
title                                                         Baby Driver
vote_average                                                          7.2
vote_count                                                         2083.0
cast                    [{'cast_id': 9, 'character': 'Baby', 'credit_i...
crew                    [{'credit_id': '55c58c009251417a21000e5d', 'de...
year                                                                 2017
director                                                     Edgar Wright
director_gender                                                      male
Name: 9462, dtype: object

In [707]:
#new_list.isna().sum()

##Cleaning the columns

In [708]:
def fix_genres_names(x):
    x = str(x)
    genres = []
    
    if 'Comedy' in x:
        genres.append('Comedy')
    if 'Action' in x:
        genres.append('Action')
    if 'Drama' in x:
        genres.append('Drama')
    if 'Crime' in x:
        genres.append('Crime')
    if 'Romance' in x:
        genres.append('Romance')
    if 'Adventure' in x:
        genres.append('Adventure')
    if 'Thriller' in x:
        genres.append('Thriller')
    if 'Fantasy' in x:
        genres.append('Fantasy')
    if 'Science Fiction' in x:
        genres.append('Science Fiction')
    if 'History' in x:
        genres.append('History')
    if 'War' in x:
        genres.append('War')
    if 'Foreign' in x:
        genres.append('Foreign')
    if 'Mystery' in x:
        genres.append('Mystery')
    if 'Family' in x:
        genres.append('Family')
    if 'Documentary' in x:
        genres.append('Documentary')
    if 'Horror' in x:
        genres.append('Horror')
    if 'Animation' in x:
        genres.append('Animation')
    if 'Western' in x:
        genres.append('Western')
    if 'Music' in x:
        genres.append('Music')
    if 'TV Movie' in x:
        genres.append('TV Movie')
    
    if genres:
        return ', '.join(genres)
    else:
        return 'nAn'

In [709]:
films['genres'] = films['genres'].apply(fix_genres_names)

In [710]:
#Drop the null values in 'Genres'
films = films.drop(films[films['genres'] == 'nAn'].index)

In [711]:
films[films['genres'] ==  'nAn']

Empty DataFrame
Columns: [genres, id, original_language, original_title, overview, popularity, production_companies, production_countries, runtime, spoken_languages, title, vote_average, vote_count, cast, crew, year, director, director_gender]
Index: []

In [712]:
#Fix production countries
films['prod_countries'] = films['production_countries'].str.extract(r"'name': '([^']*)'")
films['prod_countries'].unique()

array(['Germany', 'France', 'United Kingdom', 'Italy', 'China',
       'United States of America', 'Canada', 'Belgium', 'Iran',
       'Hong Kong', 'Dominican Republic', 'Ireland', 'Taiwan',
       'New Zealand', 'Mexico', 'Japan', 'Peru', 'Australia',
       'South Africa', 'Denmark', 'Finland', 'Spain', 'South Korea',
       'Sweden', 'Argentina', 'Austria', 'Czech Republic', 'Vietnam',
       'Switzerland', 'Trinidad and Tobago', 'Portugal', 'Russia',
       'India', 'Brazil', 'Norway', 'Aruba', 'Israel', 'Luxembourg',
       'Poland', 'Cuba', 'Malaysia', 'Bulgaria', 'Serbia', 'Greece',
       'Thailand', 'Cameroon', 'Colombia', 'Netherlands', 'Philippines',
       'Libyan Arab Jamahiriya', 'Iceland', 'Soviet Union', 'Turkey',
       'Singapore', 'Bosnia and Herzegovina', 'Czechoslovakia',
       'Martinique', 'Romania', 'Armenia', 'Egypt', 'Indonesia',
       'Hungary', 'Chile', 'Monaco', 'Uruguay', 'Algeria', 'Lithuania',
       'Palestinian Territory', 'East Germany', 'Morocco', 'Lebanon',
       'Latvia', 'United Arab Emirates', 'Slovenia', 'Cambodia',
       'Botswana', 'Pakistan', 'Congo', 'Tanzania', 'Bolivia',
       'Kazakhstan', 'Ethiopia', 'Qatar', 'Tajikistan', 'Belarus',
       'Estonia', 'Georgia', 'Mauritania', 'Burkina Faso', 'Afghanistan',
       'Croatia', 'Yugoslavia', 'Malta', 'Nicaragua', 'Ukraine',
       'Venezuela', 'Iraq', 'Liechtenstein', 'Albania', 'Macedonia'],
      dtype=object)

In [713]:
    def fix_countries(x):
        x = str(x)
        genres = []
    
        if 'Germany' in x:
            genres.append('Germany')
        if 'France' in x:
            genres.append('France')
        if 'United Kingdom' in x:
            genres.append('United Kingdom')
        if 'Italy' in x:
            genres.append('Italy')
        if 'China' in x:
            genres.append('China')
        if 'United States of America' in x:
            genres.append('United States of America')
        if 'Canada' in x:
            genres.append('Canada')
        if 'Belgium' in x:
            genres.append('Belgium')
        if 'Iran' in x:
            genres.append('Iran')
        if 'Hong Kong' in x:
            genres.append('Hong Kong')
        if 'Dominican Republic' in x:
            genres.append('Dominican Republic')
        if 'Ireland' in x:
            genres.append('Ireland')
        if 'Taiwan' in x:
            genres.append('Taiwan')
        if 'New Zealand' in x:
            genres.append('New Zealand')
        if 'Mexico' in x:
            genres.append('Mexico')
        if 'Japan' in x:
            genres.append('Japan')
        if 'Peru' in x:
            genres.append('Peru')
        if 'Australia' in x:
            genres.append('Australia')
        if 'South Africa' in x:
            genres.append('South Africa')
        if 'Denmark' in x:
            genres.append('Denmark')
        if 'Finland' in x:
            genres.append('Finland')
        if 'Spain' in x:
            genres.append('Spain')
        if 'Sweden' in x:
            genres.append('Sweden')
        if 'South Korea' in x:
            genres.append('South Korea')
        if 'Sweden' in x:
            genres.append('Sweden')
        if 'Argentina' in x:
            genres.append('Argentina')
        if 'Hungary' in x:
            genres.append('Hungary')
        if 'Austria' in x:
            genres.append('Austria')
        if 'Czech Republic' in x:
            genres.append('Czech Republic')
        if 'Vietnam' in x:
            genres.append('Vietnam')
        if 'Switzerland' in x:
            genres.append('Switzerland')
        if 'Trinidad and Tobago' in x:
            genres.append('Trinidad and Tobago')
        if 'Portugal' in x:
            genres.append('Portugal')
        if 'Russia' in x:
            genres.append('Russia')
        if 'India' in x:
            genres.append('India')
        if 'Brazil' in x:
            genres.append('Brazil')
        if 'Norway' in x:
            genres.append('Norway')
        if 'Aruba' in x:
            genres.append('Aruba')
        if 'Israel' in x:
            genres.append('Israel')
        if 'Luxembourg' in x:
            genres.append('Luxembourg')
        if 'Poland' in x:
            genres.append('Poland')
        if 'Cuba' in x:
            genres.append('Cuba')
        if 'Malaysia' in x:
            genres.append('Malaysia')
        if 'Bulgaria' in x:
            genres.append('Bulgaria')
        if 'Serbia' in x:
            genres.append('Serbia')
        if 'Greece' in x:
            genres.append('Greecee')
        if 'Thailand' in x:
            genres.append('Thailand')
        if 'Cameroon' in x:
            genres.append('Cameroon')
        if 'Colombia' in x:
            genres.append('Colombia')
        if 'Netherlands' in x:
            genres.append('Netherlands')
        if 'Philippines' in x:
            genres.append('Philippines')
        if 'Libyan Arab Jamahiriya' in x:
            genres.append('Libyan Arab Jamahiriya')
        if 'Iceland' in x:
            genres.append('Iceland')
        if 'Soviet Union' in x:
            genres.append('Soviet Union')
        if 'Turkey' in x:
            genres.append('Turkey')
        if 'Singapore' in x:
            genres.append('Singapore')
        if 'Bosnia and Herzegovina' in x:
            genres.append('Bosnia and Herzegovina')
        if 'Czechoslovakia' in x:
            genres.append('Czechoslovakia')
        if 'Martinique' in x:
            genres.append('Martinique')
        if 'Romania' in x:
            genres.append('Romania')
        if 'Armenia' in x:
            genres.append('Armenia')
        if 'Egypt' in x:
            genres.append('Egypt')
        if 'Indonesia' in x:
            genres.append('Indonesia')
        if 'Chile' in x:
            genres.append('Chile')
        if 'Monaco' in x:
            genres.append('Monaco')
        if 'Uruguay' in x:
            genres.append('Uruguay')
        if 'Algeria' in x:
            genres.append('Algeria')
        if 'Lithuania' in x:
            genres.append('Lithuania')
        if 'Palestinian Territory' in x:
            genres.append('Palestinian Territory')
        if 'East Germany' in x:
            genres.append('East Germany')
        if 'Morocco' in x:
            genres.append('Morocco')
        if 'Lebanon' in x:
            genres.append('Lebanon')
        if 'Latvia' in x:
            genres.append('Latvia')
        if 'United Arab Emirates' in x:
            genres.append('United Arab Emirates')
        if 'Slovenia' in x:
            genres.append('Slovenia')
        if 'Cambodia' in x:
            genres.append('Cambodia')
        if 'Botswana' in x:
            genres.append('Botswana')
        if 'Pakistan' in x:
            genres.append('Pakistan')
        if 'Congo' in x:
            genres.append('Congo')
        if 'Tanzania' in x:
            genres.append('Tanzania')
        if 'Bolivia' in x:
            genres.append('Bolivia')
        if 'Kazakhstan' in x:
            genres.append('Kazakhstan')
        if 'Ethiopia' in x:
            genres.append('Ethiopia')
        if 'Qatar' in x:
            genres.append('Qatar')
        if 'Tajikistan' in x:
            genres.append('Tajikistan')
        if 'Belarus' in x:
            genres.append('Belarus')
        if 'Estonia' in x:
            genres.append('Estonia')
        if 'Georgia' in x:
            genres.append('Georgia')
        if 'Mauritania' in x:
            genres.append('Mauritania')
        if 'Burkina Faso' in x:
            genres.append('Burkina Faso')
        if 'Afghanistan' in x:
            genres.append('Afghanistan')
        if 'Croatia' in x:
            genres.append('Croatia')
        if 'Yugoslavia' in x:
            genres.append('Yugoslavia')
        if 'Malta' in x:
            genres.append('Malta')
        if 'Nicaragua' in x:
            genres.append('Nicaragua')
        if 'Ukraine' in x:
            genres.append('Ukraine')
        if 'Venezuela' in x:
            genres.append('Venezuela')
        if 'Iraq' in x:
            genres.append('Iraq')
        if 'Liechtenstein' in x:
            genres.append('Liechtenstein')
        if 'Albania' in x:
            genres.append('Albania')
        if 'Macedonia' in x:
            genres.append('Macedonia')
        if genres:
            return ', '.join(genres)
        else:
            return 'Unknown'

In [714]:
films['production_countries'] = films['production_countries'].apply(fix_countries)

In [715]:
films[films['production_countries'] == 'Macedonia']

,genres,id,original_language,original_title,overview,popularity,production_companies,production_countries,runtime,spoken_languages,title,vote_average,vote_count,cast,crew,year,director,director_gender,prod_countries
9718,Drama,108827,Macedonian,Илузија,"As Macedonia faces its difficult transition, a...",0.211851,"[{'name': 'Small Moves', 'id': 63637}]",Macedonia,107.0,2,Mirage,7.0,2.0,"[{'cast_id': 4, 'character': ""Lazo / Marko's F...","[{'credit_id': '52fe4aa4c3a36847f81d9e39', 'de...",2004,Svetozar Ristovski,male,Macedonia

In [716]:
female = films[films['director_gender'] == 'female']
male_ = films[films['director_gender'] == 'male']

In [717]:
final_male = male_ 
final_female = female
final_male.drop(columns= ['crew','cast', 'director_gender','production_companies','prod_countries'], inplace=True)
final_female.drop(columns= ['crew','cast', 'director_gender' , 'production_companies', 'prod_countries'], inplace=True)

/var/folders/_s/5ccjvt852hv4ddn7j5mrvy1m0000gn/T/ipykernel_64810/2834992795.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_male.drop(columns= ['crew','cast', 'director_gender','production_companies','prod_countries'], inplace=True)
/var/folders/_s/5ccjvt852hv4ddn7j5mrvy1m0000gn/T/ipykernel_64810/2834992795.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_female.drop(columns= ['crew','cast', 'director_gender' , 'production_companies', 'prod_countries'], inplace=True)

In [718]:
final_male

,genres,id,original_language,original_title,overview,popularity,production_countries,runtime,spoken_languages,title,vote_average,vote_count,year,director
0,"Comedy, Romance",11860,English,Sabrina,An ugly duckling having undergone a remarkable...,6.677277,"Germany, United States of America",127.0,2,Sabrina,6.2,141.0,1995,Sydney Pollack
1,"Comedy, Horror",12110,English,Dracula: Dead and Loving It,When a lawyer shows up at the vampire's doorst...,5.430331,"France, United States of America",88.0,2,Dracula: Dead and Loving It,5.7,210.0,1995,Mel Brooks
2,"Action, Adventure",1408,English,Cutthroat Island,"Morgan Adams and her slave, William Shaw, are ...",7.284477,"Germany, France, Italy, United States of America",119.0,2,Cutthroat Island,5.7,137.0,1995,Renny Harlin
3,"Drama, Crime",524,English,Casino,The life of the gambling paradise – Las Vegas ...,10.137389,"France, United States of America",178.0,1,Casino,7.8,1343.0,1995,Martin Scorsese
4,"Drama, Romance",4584,English,Sense and Sensibility,"Rich Mr. Dashwood dies, leaving his second wif...",10.673167,"United Kingdom, United States of America",136.0,1,Sense and Sensibility,7.2,364.0,1995,Ang Lee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9773,"Drama, Thriller, Mystery, Horror",365432,English,The Sublet,The Sublet is a suspense driven psychological ...,1.339355,Canada,82.0,2,The Sublet,6.5,4.0,2015,John Ainslie
9774,"Action, Thriller, Mystery, Horror",45527,English,The Final Storm,A stranger named Silas flees from a devastatin...,1.270832,"Germany, Canada",92.0,1,The Final Storm,3.7,11.0,2010,Uwe Boll
9775,"Drama, Family, TV Movie",39562,English,To Be Fat Like Me,"Pretty, popular, and slim high-schooler Aly Sc...",0.767762,Canada,89.0,1,To Be Fat Like Me,5.0,12.0,2007,Douglas Barr
9776,Comedy,14008,English,Cadet Kelly,Hyperactive teenager Kelly is enrolled into a ...,4.392389,"United States of America, Canada",101.0,1,Cadet Kelly,5.2,145.0,2002,Larry Shaw
9777,"Action, Drama, Romance",30840,English,Robin Hood,"Yet another version of the classic epic, with ...",5.683753,"Germany, United Kingdom, United States of Amer...",104.0,1,Robin Hood,5.7,26.0,1991,John Irvin

In [719]:
final_female

,genres,id,original_language,original_title,overview,popularity,production_countries,runtime,spoken_languages,title,vote_average,vote_count,year,director
13,"Drama, Romance",8391,English,When Night Is Falling,"A prudish woman, working on tenure as a litera...",3.302524,Canada,96.0,1,When Night Is Falling,5.9,10.0,1995,Patricia Rozema
18,"Comedy, Romance",4482,French,Gazon maudit,"After learning of her husband's infidelities, ...",2.518051,France,95.0,2,French Twist,6.0,43.0,1995,Josiane Balasko
25,"Comedy, Drama, Family",11907,German,Keiner liebt mich,No overview found.,1.015068,Germany,104.0,1,Nobody Loves Me,5.1,5.0,1994,Doris Dörrie
44,"Drama, Romance",36834,English,Total Eclipse,"Young, wild poet Arthur Rimbaud and his mentor...",4.546552,"France, United Kingdom, Belgium",111.0,1,Total Eclipse,6.5,112.0,1995,Agnieszka Holland
62,"Drama, Romance",40156,English,Priest,Father Greg Pilkington (Linus Roache) is torn ...,1.881932,United Kingdom,98.0,1,Priest,6.4,32.0,1994,Antonia Bird
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9746,Drama,88844,English,Code Blue,"Marian, a middle aged nurse, devotes herself t...",0.547712,Netherlands,81.0,2,Code Blue,4.1,4.0,2011,Urszula Antoniak
9747,"Drama, Romance",182981,Dutch,Nude Area,"Naomi, a fifteen year-old Dutch girl from Sout...",0.420688,"Poland, Netherlands",73.0,1,Nude Area,5.0,2.0,2014,Urszula Antoniak
9751,"Comedy, Drama",30019,Norwegian,Upperdog,"As young children, half-siblings Axel and Yann...",1.056898,Norway,95.0,1,Upperdog,6.9,5.0,2009,Sara Johnsen
9755,"Comedy, Drama",366505,Spanish,El olivo,Alma’s family has been producing quality olive...,2.541633,"Germany, Spain",96.0,1,The Olive Tree,6.5,38.0,2016,Icíar Bollaín
9771,"Drama, Romance",63281,English,Про любоff,"У девушки Даши, приехавшей с подругой «покорят...",0.121844,Russia,107.0,1,Pro Lyuboff,4.0,3.0,2010,Olga Subbotina

In [720]:
final_male.to_csv('male_directed_clean.csv', index=False)

In [721]:
final_female.to_csv('female_directed_clean.csv', index=False)

In [722]:
films.to_csv('films_clean.csv', index=False)

NameError: name 'film_genre' is not defined