In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Metadata.csv')

In [4]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Variable name,Variable definition,Storage type,Data Type,Numercial Range,Number of categories,Example of categories
1,NaN,recordID,Numerical identifier for the diet record.,Numeric,Continuous,1-29351,NaN,NaN
2,NaN,orderCarni,The order of the mammal-consumer species the d...,Factor,Categorical,NaN,5,"e.g. ""Carnivora"", ""Didelphimorphia"""
3,NaN,familyCarni,The family of the mammal-consumer species the ...,Factor,Categorical,NaN,15,"e.g. ""Canidae"", ""Felidae"""
4,NaN,scientificNameCarni,The binomial name of the mammal-consumer speci...,Factor,Categorical,NaN,103,"e.g. ""Canis_lupus"", ""Panthera_onca"""

In [5]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,Variable name,Variable definition,Storage type,Data Type,Numercial Range,Number of categories,Example of categories
1,NaN,recordID,Numerical identifier for the diet record.,Numeric,Continuous,1-29351,NaN,NaN
2,NaN,orderCarni,The order of the mammal-consumer species the d...,Factor,Categorical,NaN,5,"e.g. ""Carnivora"", ""Didelphimorphia"""
3,NaN,familyCarni,The family of the mammal-consumer species the ...,Factor,Categorical,NaN,15,"e.g. ""Canidae"", ""Felidae"""
4,NaN,scientificNameCarni,The binomial name of the mammal-consumer speci...,Factor,Categorical,NaN,103,"e.g. ""Canis_lupus"", ""Panthera_onca"""
5,NaN,commonNameCarni,The common name of the mammal-consumer species...,Factor,Categorical,NaN,103,"e.g. ""African lion"", ""Cheetah"""
6,NaN,sexCarni,The sex of the mammal-consumer species that th...,Factor,Categorical,NaN,3,"""Male"", ""Female"", ""Both"""
7,NaN,lifeStageCarni,The age class of the mammal-consumer species t...,Factor,Categorical,NaN,4,"""Adult"", ""Juvenile"", ""Unspecified"", ""Sub-adult"""
8,NaN,foodType,"The broad category that the food item is from,...",Factor,Categorical,NaN,15,"e.g. ""Mammal"", ""Bird"", ""Reptile"", ""Anthropogen..."
9,NaN,orderPrey,"Taxonomic order, if appropriate, of the food i...",Factor,Categorical,NaN,60,"e.g. ""Rodentia"", ""Artiodactyla"""
10,NaN,familyPrey,"Taxonomic family, if appropriate, of the food ...",Factor,Categorical,NaN,121,"e.g. ""Muridae"", ""Cervidae"""
11,NaN,genusPrey,"Taxonomic genus, if appropriate, of the food i...",Factor,Categorical,NaN,472,"e.g. ""Apodemus"", ""Capreolus"""
12,NaN,speciesPrey,"Species epiphet, if appropriate, of the food i...",Factor,Categorical,NaN,711,"e.g. ""sylvaticus"", ""capreolus"""
13,NaN,scientificNamePrey,"Binomial name of food item record, if Genus an...",Factor,Categorical,NaN,823,"e.g. ""Apodemus_sylvaticus"", ""Capreolus_capreolus"""
14,NaN,commonNamePrey,Common name or general description of the food...,Factor,Categorical,NaN,1635,"e.g. ""Wood mouse"", ""Roe deer"""
15,NaN,anthropogenicOrigin,Specifies if the food is reported to be of ant...,Numeric,Binomial,"0 (No), 1 (Yes)",NaN,NaN
16,NaN,taxonRankPrey,Taxonomic level the food item was reported at....,Factor,Categorical,NaN,10,"e.g. ""Species"", ""Genus"""
17,NaN,percentage,The percentage of the diet in which the record...,Numeric,Compositional (%),0.01 (Low) - 100 (High),NaN,NaN
18,NaN,percentageError,Error around the quantitative importanc estima...,Numeric,Continuous (%),0-36.1,NaN,NaN
19,NaN,dataBasisFromSource,The basis from which diet records were extract...,Factor,Categorical,NaN,14,"e.g. ""Table"", ""Barchart"""
20,NaN,sampleSizeScatStomachTissue,"Sample size of the scats, stomachs or tissues ...",Numeric,Continuous,2-11478,NaN,NaN
21,NaN,sampleSizeKillsPreyItems,Sample size of prey items extracted from scats...,Numeric,Continuous,3-23824,NaN,NaN
22,NaN,startYear,"The year when sampling began, if given in the ...",Numeric,Integer,1933-2017,NaN,NaN
23,NaN,endYear,"The year when sampling ended, if given in the ...",Numeric,Integer,1946-2017,NaN,NaN
24,NaN,startMonth,The month in the start year when sampling bega...,Numeric,Categorical,NaN,12,"e.g. ""January"", ""December"""
25,NaN,endMonth,"The month in the end year when sampling ended,...",Numeric,Categorical,NaN,12,"e.g. ""January"", ""December"""
26,NaN,fixedBetweenMonths,This specifies whether a the diet was carried ...,Numeric,Binary,0 (No) - 1 (Yes),NaN,NaN
27,NaN,startDayOfYear,Start day of the start month in the start year...,Numeric,Integer,1 to 30,NaN,NaN
28,NaN,endDayOfYear,"End day, of the end month, in the end year, if...",Numeric,Integer,2 to 31,NaN,NaN
29,NaN,season,The season in which the food item was reported...,Factor,Categorical,NaN,45,"e.g. ""Summer"", ""Winter"", ""Pup-rearing"", ""Prey ..."
30,NaN,minimumElevationInMeters,The minimum height above sea level of the stud...,Numeric,Continuous (m),0-4543,NaN,NaN
31,NaN,maximumElevationInMeters,The maximum height above sea level of the stud...,Numeric,Continuous (m),0-8156,NaN,NaN
32,NaN,geographicArea,A description of a larger geographic region wi...,Factor,Categorical,NaN,139,"e.g. ""Greater Yellowstone Ecosystem"", ""Himalayas"""
33,NaN,country,The name of the country or major administrativ...,Factor,Categorical,NaN,97,"e.g. ""Spain"", ""Australia"""
34,NaN,stateProvice,The name of the next smaller administrative re...,Factor,Categorical,NaN,156,"e.g. ""Oregon"", ""Perak"""
35,NaN,county,The full name of the next smaller administrati...,Factor,Categorical,NaN,81,"e.g. ""Grosseto"", ""Wiltshire"""
36,NaN,municipality,The full name of the next smaller administrati...,Factor,Categorical,NaN,118,"e.g. ""Sydney"", ""Zurich"""
37,NaN,verbatimLocality,A description of the place in which a study oc...,Factor,Categorical,NaN,344,"e.g. ""Wildlife Management Area in the Makgadik..."
38,NaN,protectedAreaHigher,The name of an area with some designated level...,Factor,Categorical,NaN,256,"e.g. ""Tai National Park"", ""Wolong Reserve"""
39,NaN,protectedAreaLower,The name of a smaller unit within a larger are...,Factor,Categorical,NaN,3,"""Kalahari Gemsbok National Park"", ""Postberg Na..."
40,NaN,island,The name of the island on or near which the st...,Factor,Categorical,NaN,3,"""Balearic Island Archipelago"", ""Canary Islands..."
41,NaN,islandGroup,The name of the island group in which the stud...,Factor,Categorical,NaN,28,"e.g. ""Sardinia"", "" Mallorca"""
42,NaN,sampleSizeUnit,"Size of the study area (km2), as given in the ...",Numeric,Continuous (km2),0.034 - 100000,NaN,NaN
43,NaN,decimalLatitude,Latitudinal vaue of the study area.,Numeric,Decimal degrees,174.1 to -169.4,NaN,NaN
44,NaN,decimalLongitude,Longitudinal value of the study area.,Numeric,Decimal degrees,81.6 to -55,NaN,NaN
45,NaN,georeferenceSources,Source of the coordinates for the study area. ...,Factor,Categorical,NaN,4,"""Reported"", ""GoogleMaps"", ""GoogleMaps(PrimaryR..."
46,NaN,samplingProtocol,The sample material from where food items were...,Factor,Categorical,NaN,20,"e.g. ""Scat"", ""Prey items in stomachs"", ""Blood"""
47,NaN,methodQuantification,The method used to calculate the importance of...,Factor,Categorical,NaN,9,"e.g. ""Biomass consumed (%)"", ""Volume in source..."
48,NaN,authorSource,"Lead author of the primary reference, recorded...",Factor,Categorical,NaN,611,"e.g. ""Ackerman, B."", ""deVos, A."""
49,NaN,yearSource,The year of the paper publication in the journal.,Factor,Continuous,1952 to 2019,NaN,NaN
50,NaN,titleSource,"The name of the paper, as given in the journal.",Factor,Categorical,NaN,719,"e.g. ""Wolves, white-tiled deer, and beaver: Im..."
51,NaN,journalSource,The name of the journal which the paper was st...,Factor,Categorical,NaN,196,"e.g. ""Journal of Zoology"", ""Ursus"""
52,NaN,sourcePrimaryReference,The citation of the paper where the prey item ...,Factor,Categorical,NaN,719,"e.g. ""Zuercher, Gerald L., Philip S. Gipson, a..."
53,NaN,sourceCollectionReference,The citation of the paper where the prey item ...,Factor,Categorical,NaN,686,"e.g. ""Zuercher, Gerald L., Philip S. Gipson, a..."

In [7]:
df.drop(columns='Unnamed: 0', inplace=True)

In [8]:
df

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Variable name,Variable definition,Storage type,Data Type,Numercial Range,Number of categories,Example of categories
1,recordID,Numerical identifier for the diet record.,Numeric,Continuous,1-29351,NaN,NaN
2,orderCarni,The order of the mammal-consumer species the d...,Factor,Categorical,NaN,5,"e.g. ""Carnivora"", ""Didelphimorphia"""
3,familyCarni,The family of the mammal-consumer species the ...,Factor,Categorical,NaN,15,"e.g. ""Canidae"", ""Felidae"""
4,scientificNameCarni,The binomial name of the mammal-consumer speci...,Factor,Categorical,NaN,103,"e.g. ""Canis_lupus"", ""Panthera_onca"""
5,commonNameCarni,The common name of the mammal-consumer species...,Factor,Categorical,NaN,103,"e.g. ""African lion"", ""Cheetah"""
6,sexCarni,The sex of the mammal-consumer species that th...,Factor,Categorical,NaN,3,"""Male"", ""Female"", ""Both"""
7,lifeStageCarni,The age class of the mammal-consumer species t...,Factor,Categorical,NaN,4,"""Adult"", ""Juvenile"", ""Unspecified"", ""Sub-adult"""
8,foodType,"The broad category that the food item is from,...",Factor,Categorical,NaN,15,"e.g. ""Mammal"", ""Bird"", ""Reptile"", ""Anthropogen..."
9,orderPrey,"Taxonomic order, if appropriate, of the food i...",Factor,Categorical,NaN,60,"e.g. ""Rodentia"", ""Artiodactyla"""
10,familyPrey,"Taxonomic family, if appropriate, of the food ...",Factor,Categorical,NaN,121,"e.g. ""Muridae"", ""Cervidae"""
11,genusPrey,"Taxonomic genus, if appropriate, of the food i...",Factor,Categorical,NaN,472,"e.g. ""Apodemus"", ""Capreolus"""
12,speciesPrey,"Species epiphet, if appropriate, of the food i...",Factor,Categorical,NaN,711,"e.g. ""sylvaticus"", ""capreolus"""
13,scientificNamePrey,"Binomial name of food item record, if Genus an...",Factor,Categorical,NaN,823,"e.g. ""Apodemus_sylvaticus"", ""Capreolus_capreolus"""
14,commonNamePrey,Common name or general description of the food...,Factor,Categorical,NaN,1635,"e.g. ""Wood mouse"", ""Roe deer"""
15,anthropogenicOrigin,Specifies if the food is reported to be of ant...,Numeric,Binomial,"0 (No), 1 (Yes)",NaN,NaN
16,taxonRankPrey,Taxonomic level the food item was reported at....,Factor,Categorical,NaN,10,"e.g. ""Species"", ""Genus"""
17,percentage,The percentage of the diet in which the record...,Numeric,Compositional (%),0.01 (Low) - 100 (High),NaN,NaN
18,percentageError,Error around the quantitative importanc estima...,Numeric,Continuous (%),0-36.1,NaN,NaN
19,dataBasisFromSource,The basis from which diet records were extract...,Factor,Categorical,NaN,14,"e.g. ""Table"", ""Barchart"""
20,sampleSizeScatStomachTissue,"Sample size of the scats, stomachs or tissues ...",Numeric,Continuous,2-11478,NaN,NaN
21,sampleSizeKillsPreyItems,Sample size of prey items extracted from scats...,Numeric,Continuous,3-23824,NaN,NaN
22,startYear,"The year when sampling began, if given in the ...",Numeric,Integer,1933-2017,NaN,NaN
23,endYear,"The year when sampling ended, if given in the ...",Numeric,Integer,1946-2017,NaN,NaN
24,startMonth,The month in the start year when sampling bega...,Numeric,Categorical,NaN,12,"e.g. ""January"", ""December"""
25,endMonth,"The month in the end year when sampling ended,...",Numeric,Categorical,NaN,12,"e.g. ""January"", ""December"""
26,fixedBetweenMonths,This specifies whether a the diet was carried ...,Numeric,Binary,0 (No) - 1 (Yes),NaN,NaN
27,startDayOfYear,Start day of the start month in the start year...,Numeric,Integer,1 to 30,NaN,NaN
28,endDayOfYear,"End day, of the end month, in the end year, if...",Numeric,Integer,2 to 31,NaN,NaN
29,season,The season in which the food item was reported...,Factor,Categorical,NaN,45,"e.g. ""Summer"", ""Winter"", ""Pup-rearing"", ""Prey ..."
30,minimumElevationInMeters,The minimum height above sea level of the stud...,Numeric,Continuous (m),0-4543,NaN,NaN
31,maximumElevationInMeters,The maximum height above sea level of the stud...,Numeric,Continuous (m),0-8156,NaN,NaN
32,geographicArea,A description of a larger geographic region wi...,Factor,Categorical,NaN,139,"e.g. ""Greater Yellowstone Ecosystem"", ""Himalayas"""
33,country,The name of the country or major administrativ...,Factor,Categorical,NaN,97,"e.g. ""Spain"", ""Australia"""
34,stateProvice,The name of the next smaller administrative re...,Factor,Categorical,NaN,156,"e.g. ""Oregon"", ""Perak"""
35,county,The full name of the next smaller administrati...,Factor,Categorical,NaN,81,"e.g. ""Grosseto"", ""Wiltshire"""
36,municipality,The full name of the next smaller administrati...,Factor,Categorical,NaN,118,"e.g. ""Sydney"", ""Zurich"""
37,verbatimLocality,A description of the place in which a study oc...,Factor,Categorical,NaN,344,"e.g. ""Wildlife Management Area in the Makgadik..."
38,protectedAreaHigher,The name of an area with some designated level...,Factor,Categorical,NaN,256,"e.g. ""Tai National Park"", ""Wolong Reserve"""
39,protectedAreaLower,The name of a smaller unit within a larger are...,Factor,Categorical,NaN,3,"""Kalahari Gemsbok National Park"", ""Postberg Na..."
40,island,The name of the island on or near which the st...,Factor,Categorical,NaN,3,"""Balearic Island Archipelago"", ""Canary Islands..."
41,islandGroup,The name of the island group in which the stud...,Factor,Categorical,NaN,28,"e.g. ""Sardinia"", "" Mallorca"""
42,sampleSizeUnit,"Size of the study area (km2), as given in the ...",Numeric,Continuous (km2),0.034 - 100000,NaN,NaN
43,decimalLatitude,Latitudinal vaue of the study area.,Numeric,Decimal degrees,174.1 to -169.4,NaN,NaN
44,decimalLongitude,Longitudinal value of the study area.,Numeric,Decimal degrees,81.6 to -55,NaN,NaN
45,georeferenceSources,Source of the coordinates for the study area. ...,Factor,Categorical,NaN,4,"""Reported"", ""GoogleMaps"", ""GoogleMaps(PrimaryR..."
46,samplingProtocol,The sample material from where food items were...,Factor,Categorical,NaN,20,"e.g. ""Scat"", ""Prey items in stomachs"", ""Blood"""
47,methodQuantification,The method used to calculate the importance of...,Factor,Categorical,NaN,9,"e.g. ""Biomass consumed (%)"", ""Volume in source..."
48,authorSource,"Lead author of the primary reference, recorded...",Factor,Categorical,NaN,611,"e.g. ""Ackerman, B."", ""deVos, A."""
49,yearSource,The year of the paper publication in the journal.,Factor,Continuous,1952 to 2019,NaN,NaN
50,titleSource,"The name of the paper, as given in the journal.",Factor,Categorical,NaN,719,"e.g. ""Wolves, white-tiled deer, and beaver: Im..."
51,journalSource,The name of the journal which the paper was st...,Factor,Categorical,NaN,196,"e.g. ""Journal of Zoology"", ""Ursus"""
52,sourcePrimaryReference,The citation of the paper where the prey item ...,Factor,Categorical,NaN,719,"e.g. ""Zuercher, Gerald L., Philip S. Gipson, a..."
53,sourceCollectionReference,The citation of the paper where the prey item ...,Factor,Categorical,NaN,686,"e.g. ""Zuercher, Gerald L., Philip S. Gipson, a..."

In [ ]:
df.rename(columns={"Unnamed: 1": "variable_name", "Unnamed: 2":'variable_definition', 'Unnamed: 3':'storage_type', 'Unnamed: 4':'data_type',
                   'Unnamed: 5':'Numercial Range', 'Unnamed: 6':'Number of categories', 'Unnamed: 7':'Example of categories'})